# Generated by Django 5.0.2 on 2024-03-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rate',
            constraint=models.UniqueConstraint(fields=('user', 'anime'), name='unique_user_anime'),
        ),
    ]
