# Generated by Django 5.0.2 on 2024-04-25 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rate_rewatched_alter_rate_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='completed',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
