version: "3"

services:
  db:
    container_name: hikilist-postgres

    restart: always

    image: postgres:16-alpine

    volumes:
      - ${DB_DATA_PATH}:/etc/pgdata

    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      PGDATA: /etc/pgdata

  web:
    container_name: hikilist-web

    restart: always

    build: app
    
    env_file:
      - .env.web

    volumes:
      - "${WEB_MEDIA_PATH}:/srv/app/media"
      - "${WEB_ASSETS_PATH}:/srv/app/assets"
    
    depends_on:
      - db

    ports:
      - "${WEB_PORT:-127.0.0.1:8000}:8000"