version: 3

tasks:
  predev:
    desc: Setting up backend development environment
    directory: app
    cmds:
      - py -m venv venv
      - pip install -r requirements.txt

  start:
    desc: Start docker compose
    cmds:
      - docker-compose -f compose.dev.yaml up
  
  start-detach:
    desc: Start docker compose
    cmds:
      - docker-compose -f compose.dev.yaml up --build -d 
  
  build:
    desc: Build docker compose
    cmds:
      - docker-compose -f compose.dev.yaml build
  
  start-local:
    desc: Start backend
    cmds:
      - py app/manage.py runserver