# Generated by Django 5.0.2 on 2024-03-26 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
            ],
            options={
                'db_table': 'formats',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
            ],
            options={
                'db_table': 'studios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malId', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', models.TextField(max_length=1000)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('episodes_released', models.PositiveIntegerField(blank=True, null=True)),
                ('announcement', models.DateField(blank=True, null=True)),
                ('started', models.DateField(blank=True, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('related', models.ManyToManyField(blank=True, to='animes.anime')),
                ('format', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animes.format')),
                ('genres', models.ManyToManyField(blank=True, to='animes.genre')),
                ('studios', models.ManyToManyField(blank=True, to='animes.studio')),
            ],
            options={
                'db_table': 'animes',
                'ordering': ['id'],
            },
        ),
    ]
