# Generated by Django 5.0.2 on 2024-03-09 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_alter_animeuserrate_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='animeuserrate',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='studio',
            options={'ordering': ['id']},
        ),
    ]
