# Generated by Django 5.0.2 on 2024-03-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0004_alter_anime_options_alter_animeuserrate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='status',
            field=models.GeneratedField(db_persist=False, expression=models.Case(models.When(episodes_released__isnull=True, then=models.Value('Анонсировано')), models.When(models.Q(('episodes', models.F('episodes_released'))), then=models.Value('Вышло')), default=models.Value('Выходит')), output_field=models.CharField(max_length=32)),
        ),
    ]
