# Generated by Django 5.0.2 on 2024-02-08 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malId', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', models.TextField(max_length=1000)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters')),
                ('desctiption', models.TextField(blank=True, max_length=10000, null=True)),
                ('episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('episodes_released', models.PositiveIntegerField(blank=True, null=True)),
                ('announcement', models.DateField(blank=True, null=True)),
                ('started', models.DateField(blank=True, null=True)),
                ('released', models.DateField(blank=True, null=True)),
                ('related', models.ManyToManyField(blank=True, to='animes.anime')),
                ('format', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animes.format')),
                ('genres', models.ManyToManyField(blank=True, to='animes.genre')),
                ('studios', models.ManyToManyField(blank=True, to='animes.studio')),
            ],
        ),
        migrations.CreateModel(
            name='AnimeUserRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('list', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animes.list')),
            ],
        ),
    ]
